"""add adhesion date to visitors

Revision ID: 26cd96c97469
Revises: b1e2f3a4c5d6
Create Date: 2026-07-26 15:57:35.691978

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "26cd96c97469"
down_revision: Union[str, None] = "b1e2f3a4c5d6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("visitors", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("adhesion_date", sa.Date(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("visitors", schema=None) as batch_op:
        batch_op.drop_column("adhesion_date")

    # ### end Alembic commands ###
