"""visitors firstlast name etc

Revision ID: 3f8661a94b71
Revises: 3ece58690a2b
Create Date: 2024-10-08 01:41:40.609076

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3f8661a94b71"
down_revision: Union[str, None] = "3ece58690a2b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("visitors", schema=None) as batch_op:
        batch_op.add_column(sa.Column("first_name", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("last_name", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("nick", sa.String(), nullable=True))
        batch_op.alter_column(
            "email", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.drop_column("name")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("visitors", schema=None) as batch_op:
        batch_op.add_column(sa.Column("name", sa.VARCHAR(), nullable=False))
        batch_op.alter_column(
            "email", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.drop_column("nick")
        batch_op.drop_column("last_name")
        batch_op.drop_column("first_name")

    # ### end Alembic commands ###
