"""add self edit uuid to visitors

Revision ID: 41bc38f05eeb
Revises: a1b2c3d4e5f6
Create Date: 2026-08-23 01:36:24.312601

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "41bc38f05eeb"
down_revision: Union[str, None] = "a1b2c3d4e5f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("visitors", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("self_edit_uuid", sa.String(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("visitors", schema=None) as batch_op:
        batch_op.drop_column("self_edit_uuid")

    # ### end Alembic commands ###
