"""Add availability

Revision ID: 7faead614f4f
Revises: 23d1ce2fb8bc
Create Date: 2026-08-31 23:44:28.346419

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7faead614f4f"
down_revision: Union[str, None] = "23d1ce2fb8bc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "staff",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("discord_id", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_staff")),
        sa.UniqueConstraint("discord_id", name=op.f("uq_staff_discord_id")),
    )
    op.create_table(
        "availabilities",
        sa.Column("staff_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("OPENING", "CLOSING", "ALL_DAY", name="type"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["staff_id"],
            ["staff.id"],
            name=op.f("fk_availabilities_staff_id_staff"),
        ),
        sa.PrimaryKeyConstraint(
            "staff_id", "date", name=op.f("pk_availabilities")
        ),
    )
    with op.batch_alter_table("auth_tokens", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_auth_tokens_staff_id_staffs"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_auth_tokens_staff_id_staff"),
            "staff",
            ["staff_id"],
            ["id"],
        )
    op.drop_table("staffs")
    op.drop_table("bookings")

    with op.batch_alter_table("visits", schema=None) as batch_op:
        batch_op.alter_column(
            "opening_id", existing_type=sa.INTEGER(), nullable=True
        )
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("visits", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True
        )
        batch_op.alter_column(
            "opening_id", existing_type=sa.INTEGER(), nullable=False
        )

    with op.batch_alter_table("auth_tokens", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_auth_tokens_staff_id_staff"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_auth_tokens_staff_id_staffs"),
            "staffs",
            ["staff_id"],
            ["id"],
        )

    op.create_table(
        "bookings",
        sa.Column("visitor_id", sa.INTEGER(), nullable=False),
        sa.Column("opening_id", sa.INTEGER(), nullable=False),
        sa.Column("extras", sa.INTEGER(), nullable=False),
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bookings")),
    )
    op.create_table(
        "staffs",
        sa.Column("name", sa.VARCHAR(), nullable=False),
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("discord_id", sa.VARCHAR(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_staffs")),
        sa.UniqueConstraint("discord_id", name=op.f("uq_staffs_discord_id")),
    )
    op.drop_table("availabilities")
    op.drop_table("staff")
    # ### end Alembic commands ###
