"""auth token and staff discord id

Revision ID: 9783e35f3a94
Revises: 48b2a44aad5f
Create Date: 2024-11-13 23:30:56.062323

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9783e35f3a94"
down_revision: Union[str, None] = "48b2a44aad5f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_tokens",
        sa.Column("staff_id", sa.Integer(), nullable=True),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["staff_id"],
            ["staffs.id"],
            name=op.f("fk_auth_tokens_staff_id_staffs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_tokens")),
    )
    with op.batch_alter_table("staffs", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("discord_id", sa.String(), nullable=False)
        )
        batch_op.create_unique_constraint(
            batch_op.f("uq_staffs_discord_id"), ["discord_id"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("staffs", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("uq_staffs_discord_id"), type_="unique"
        )
        batch_op.drop_column("discord_id")

    op.drop_table("auth_tokens")
    # ### end Alembic commands ###
