"""add stream state table

Revision ID: afb02b34bacc
Revises: fcd69a1713c5
Create Date: 2026-07-11 23:35:06.964110

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "afb02b34bacc"
down_revision: Union[str, None] = "fcd69a1713c5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stream_states",
        sa.Column("game", sa.String(), nullable=False),
        sa.Column("inactive_since", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stream_states")),
        sa.UniqueConstraint("game", name=op.f("uq_stream_states_game")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("stream_states")
    # ### end Alembic commands ###
